"""Cut segments, crop to 9:16, and burn captions using FFmpeg."""
from __future__ import annotations

import subprocess
from pathlib import Path
from typing import TYPE_CHECKING

from .color_presets import get_color_filter

if TYPE_CHECKING:
    from .tracking import TrackPoint


def _get_video_dimensions(
    video_path: Path,
) -> tuple[int, int] | None:
    """Return (width, height) via ffprobe, or None."""
    try:
        out = subprocess.run(
            [
                "ffprobe",
                "-v",
                "error",
                "-select_streams",
                "v:0",
                "-show_entries",
                "stream=width,height",
                "-of",
                "csv=p=0",
                str(video_path.resolve()),
            ],
            capture_output=True,
            text=True,
            timeout=10,
        )

        if out.returncode != 0 or not out.stdout.strip():
            return None

        parts = out.stdout.strip().split(",")

        if len(parts) >= 2:
            return int(parts[0]), int(parts[1])

    except Exception:
        pass

    return None


def _apply_color_to_filter_complex(
    filter_complex: str,
    color_filter: str | None,
) -> tuple[str, str]:
    """
    Apply color grading to a filter_complex graph that ends in [out].

    Returns:
        (updated_filter_complex, output_label)
    """
    if not color_filter:
        return filter_complex, "[out]"

    return (
        filter_complex
        + f";[out]{color_filter}[out_color]",
        "[out_color]",
    )


def make_short(
    video_path: Path,
    start_sec: float,
    end_sec: float,
    output_path: Path,
    srt_path: Path | None = None,
    width: int = 1080,
    height: int = 1920,
    focus_x: float | None = None,

    # NEW:
    # Dynamic horizontal focus generated by estimate_focus_track().
    #
    # Example:
    # [
    #     (0.0, 0.25),
    #     (0.5, 0.28),
    #     (1.0, 0.72),
    # ]
    focus_track: list[tuple[float, float]] | None = None,

    crop_mode: str = "center",
    focus_region: str = "full",
    manual_top: float | None = None,
    manual_bottom: float | None = None,
    manual_left: float | None = None,
    manual_right: float | None = None,
    webcam_bbox: tuple[float, float, float, float] | None = None,
    chat_bbox: tuple[float, float, float, float] | None = None,
    center_bbox: tuple[float, float, float, float] | None = None,
    event_bbox: tuple[float, float, float, float] | None = None,
    letterbox_full_width: bool = False,
    color_preset: str = "none",
) -> Path:
    """
    Extract [start_sec, end_sec], crop to height x width (9:16),
    optionally burn SRT.

    When focus_track is provided for center/full mode, use the
    dynamic renderer so the crop follows faces horizontally.

    letterbox_full_width:
        If True, scale to full width 1080 and pad top/bottom
        to 1920 instead of horizontally cropping.
    """

    duration = end_sec - start_sec
    color_filter = get_color_filter(color_preset)

    output_path = Path(output_path)
    output_path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    # ---------------------------------------------------------
    # Dynamic Smart Crop
    # ---------------------------------------------------------
    #
    # focus.py now generates horizontal tracking points over time.
    # If we have them, render using the dynamic crop engine.
    #
    # For now this is intentionally enabled only for the normal
    # center/full-frame Reels layout. Other special layouts keep
    # using their existing FFmpeg logic.
    # ---------------------------------------------------------

    if (
        focus_track
        and crop_mode == "center"
        and focus_region == "full"
        and manual_top is None
        and manual_bottom is None
        and manual_left is None
        and manual_right is None
        and not letterbox_full_width
    ):
        return make_short_focus_track(
            video_path=video_path,
            start_sec=start_sec,
            end_sec=end_sec,
            output_path=output_path,
            focus_track=focus_track,
            srt_path=srt_path,
            width=width,
            height=height,
            color_preset=color_preset,
        )

    # Optional pre-crop used for screen recordings where a
    # vertical short is centered on the screen.
    if focus_region == "center":

        # 70% width, 90% height, centered.
        center_crop = (
            "crop="
            "in_w*0.7:"
            "in_h*0.9:"
            "in_w*0.15:"
            "in_h*0.05"
        )

    else:
        center_crop = None

    # Optional manual region.
    manual_crop = None

    if (
        manual_top is not None
        and manual_bottom is not None
    ):
        t = max(
            0.0,
            min(
                manual_top,
                manual_bottom,
            ),
        )

        b = min(
            1.0,
            max(
                manual_top,
                manual_bottom,
            ),
        )

        if b - t > 0.01:

            if (
                manual_left is not None
                and manual_right is not None
            ):

                l_ = max(
                    0.0,
                    min(
                        manual_left,
                        manual_right,
                    ),
                )

                r_ = min(
                    1.0,
                    max(
                        manual_left,
                        manual_right,
                    ),
                )

                if r_ - l_ > 0.01:
                    w_expr = (
                        f"in_w*{r_ - l_:.4f}"
                    )

                    h_expr = (
                        f"in_h*{b - t:.4f}"
                    )

                    x_expr = (
                        f"in_w*{l_:.4f}"
                    )

                    y_expr = (
                        f"in_h*{t:.4f}"
                    )

                    manual_crop = (
                        f"crop={w_expr}:"
                        f"{h_expr}:"
                        f"{x_expr}:"
                        f"{y_expr}"
                    )

            if manual_crop is None:
                h_expr = (
                    f"in_h*{b - t:.4f}"
                )

                y_expr = (
                    f"in_h*{t:.4f}"
                )

                manual_crop = (
                    f"crop=in_w:"
                    f"{h_expr}:"
                    f"0:"
                    f"{y_expr}"
                )

    if crop_mode == "bottom_strip_rotate":

        vf_parts = [
            "crop=in_w:in_h/2:0:in_h/2",
            "transpose=1",
            "scale=1080:-1",
            (
                "crop=1080:1920:"
                "(in_w-1080)/2:"
                "(in_h-1920)/2"
            ),
        ]

        if manual_crop:
            vf_parts = (
                [manual_crop]
                + vf_parts
            )

        elif center_crop:
            vf_parts = (
                [center_crop]
                + vf_parts
            )

    elif crop_mode == "bottom_split_stack":
        vf_parts = None

    elif crop_mode == "bottom_split_stack_swapped":
        vf_parts = None

    elif crop_mode == "webcam_chat_stack":
        vf_parts = None

    elif crop_mode == "event":

        if letterbox_full_width:
            scale_final = (
                "scale=1080:-1,"
                "pad=1080:1920:"
                "0:(1920-ih)/2:black"
            )

        else:
            scale_final = (
                f"scale={width}:{height}:"
                "force_original_aspect_ratio=increase,"
                f"crop={width}:{height}"
            )

        if event_bbox is not None:
            xmin, ymin, xmax, ymax = event_bbox

            rw = max(
                0.02,
                xmax - xmin,
            )

            rh = max(
                0.02,
                ymax - ymin,
            )

            event_crop = (
                f"crop="
                f"in_w*{rw:.4f}:"
                f"in_h*{rh:.4f}:"
                f"in_w*{xmin:.4f}:"
                f"in_h*{ymin:.4f}"
            )

            if focus_region == "center":

                center_crop_str = (
                    "crop="
                    "in_w*0.7:"
                    "in_h*0.9:"
                    "in_w*0.15:"
                    "in_h*0.05"
                )

                vf_parts = [
                    center_crop_str,
                    event_crop,
                    scale_final,
                ]

            else:
                vf_parts = [
                    event_crop,
                    scale_final,
                ]

        else:
            vf_parts = (
                [
                    center_crop,
                    scale_final,
                ]
                if center_crop
                else [scale_final]
            )

    else:

        # center / speaker / event fallback

        if letterbox_full_width:
            scale_final = (
                "scale=1080:-1,"
                "pad=1080:1920:"
                "0:(1920-ih)/2:black"
            )

        else:
            scale_final = (
                f"scale={width}:{height}:"
                "force_original_aspect_ratio=increase,"
                f"crop={width}:{height}"
            )

        if event_bbox is not None:

            xmin, ymin, xmax, ymax = event_bbox

            rw = xmax - xmin
            rh = ymax - ymin

            if rw < 0.02:
                rw = 0.02

            if rh < 0.02:
                rh = 0.02

            event_crop = (
                f"crop="
                f"in_w*{rw:.4f}:"
                f"in_h*{rh:.4f}:"
                f"in_w*{xmin:.4f}:"
                f"in_h*{ymin:.4f}"
            )

            vf_parts = [
                event_crop,
                scale_final,
            ]

        elif focus_x is None:

            vf_parts = []

            if manual_crop:
                vf_parts.append(
                    manual_crop
                )

            elif center_crop:
                vf_parts.append(
                    center_crop
                )

            vf_parts.append(
                scale_final
            )

        else:

            cx_expr = (
                f"in_w*{focus_x:.3f}"
            )

            x_expr = (
                f"min("
                f"max("
                f"{cx_expr}-{width / 2},"
                f"0"
                f"),"
                f"in_w-{width}"
                f")"
            )

            crop = (
                f"crop="
                f"{width}:"
                f"{height}:"
                f"{x_expr}:"
                f"(in_h-{height})/2"
            )

            vf_parts = []

            if manual_crop:
                vf_parts.append(
                    manual_crop
                )

            elif center_crop:
                vf_parts.append(
                    center_crop
                )

            vf_parts.append(
                f"scale=-1:{height}:"
                "force_original_aspect_ratio=increase"
            )

            vf_parts.append(
                crop
            )

    if (
        color_filter
        and vf_parts is not None
    ):
        vf_parts.append(
            color_filter
        )

    if (
        srt_path
        and srt_path.exists()
    ):
        srt_name = srt_path.name

        if vf_parts is not None:
            vf_parts.append(
                "subtitles="
                f"filename="
                f"{_escape_subtitles_path(srt_name)}"
            )

    vf = (
        ",".join(vf_parts)
        if vf_parts
        else None
    )

    out_dir = output_path.parent

    # ---------------------------------------------------------
    # Webcam + chat stacking layout
    # ---------------------------------------------------------

    if (
        crop_mode == "webcam_chat_stack"
        and webcam_bbox is not None
        and chat_bbox is not None
    ):

        wl, wt, wr, wb = webcam_bbox
        cl, ct, cr, cb = chat_bbox

        rw_w = max(
            0.01,
            wr - wl,
        )

        rh_w = max(
            0.01,
            wb - wt,
        )

        rw_c = max(
            0.01,
            cr - cl,
        )

        rh_c = max(
            0.01,
            cb - ct,
        )

        src_wh = _get_video_dimensions(
            video_path
        )

        if src_wh is not None:

            W, H = src_wh

            h_w = max(
                1,
                min(
                    1920,
                    round(
                        1080
                        * (H * rh_w)
                        / (W * rw_w)
                    ),
                ),
            )

            h_c = max(
                1,
                min(
                    1920,
                    round(
                        1080
                        * (H * rh_c)
                        / (W * rw_c)
                    ),
                ),
            )

        else:

            h_w = max(
                1,
                min(
                    1920,
                    round(
                        1080
                        * rh_w
                        / rw_w
                    ),
                ),
            )

            h_c = max(
                1,
                min(
                    1920,
                    round(
                        1080
                        * rh_c
                        / rw_c
                    ),
                ),
            )

        def even(v: int) -> int:
            return max(
                2,
                (v // 2) * 2,
            )

        h_w = even(h_w)
        h_c = even(h_c)

        if center_bbox is not None:
            ml, mt, mr, mb = center_bbox

        else:
            ml, mt, mr, mb = (
                0.25,
                0.25,
                0.75,
                0.75,
            )

        rw_m = max(
            0.01,
            mr - ml,
        )

        rh_m = max(
            0.01,
            mb - mt,
        )

        if h_w + h_c < 1920:

            h_mid = even(
                1920
                - h_w
                - h_c
            )

            fc = (
                f"[0:v]"
                f"crop="
                f"in_w*{rw_w:.4f}:"
                f"in_h*{rh_w:.4f}:"
                f"in_w*{wl:.4f}:"
                f"in_h*{wt:.4f}"
                f"[wc];"

                f"[wc]"
                f"scale=1080:{h_w}:"
                f"force_original_aspect_ratio=increase,"
                f"crop=1080:{h_w}:0:0"
                f"[wc2];"

                f"[0:v]"
                f"crop="
                f"in_w*{rw_c:.4f}:"
                f"in_h*{rh_c:.4f}:"
                f"in_w*{cl:.4f}:"
                f"in_h*{ct:.4f}"
                f"[ch];"

                f"[ch]"
                f"scale=1080:{h_c}:"
                f"force_original_aspect_ratio=increase,"
                f"crop=1080:{h_c}:0:0"
                f"[ch2];"

                f"[0:v]"
                f"crop="
                f"in_w*{rw_m:.4f}:"
                f"in_h*{rh_m:.4f}:"
                f"in_w*{ml:.4f}:"
                f"in_h*{mt:.4f}"
                f"[mid];"

                f"[mid]"
                f"scale=1080:{h_mid}:"
                f"force_original_aspect_ratio=decrease,"
                f"pad=1080:{h_mid}:"
                f"(ow-iw)/2:"
                f"(oh-ih)/2:black"
                f"[mid2];"

                "[wc2][mid2][ch2]"
                "vstack=inputs=3[out]"
            )

        else:

            scale = (
                1920
                / (h_w + h_c)
            )

            h_w_new = even(
                max(
                    1,
                    round(
                        h_w * scale
                    ),
                )
            )

            h_c_new = (
                1920
                - h_w_new
            )

            fc = (
                f"[0:v]"
                f"crop="
                f"in_w*{rw_w:.4f}:"
                f"in_h*{rh_w:.4f}:"
                f"in_w*{wl:.4f}:"
                f"in_h*{wt:.4f}"
                f"[wc];"

                f"[wc]"
                f"scale=1080:{h_w_new}:"
                f"force_original_aspect_ratio=increase,"
                f"crop=1080:{h_w_new}:0:0"
                f"[wc2];"

                f"[0:v]"
                f"crop="
                f"in_w*{rw_c:.4f}:"
                f"in_h*{rh_c:.4f}:"
                f"in_w*{cl:.4f}:"
                f"in_h*{ct:.4f}"
                f"[ch];"

                f"[ch]"
                f"scale=1080:{h_c_new}:"
                f"force_original_aspect_ratio=increase,"
                f"crop=1080:{h_c_new}:0:0"
                f"[ch2];"

                "[wc2][ch2]"
                "vstack=inputs=2[out]"
            )

        fc, fc_output_label = _apply_color_to_filter_complex(
            fc,
            color_filter,
        )

        cmd = [
            "ffmpeg",
            "-y",
            "-ss",
            str(start_sec),
            "-i",
            str(video_path.resolve()),
            "-t",
            str(duration),
            "-avoid_negative_ts",
            "make_zero",
            "-filter_complex",
            fc,
            "-map",
            fc_output_label,
            "-map",
            "0:a?",
            "-c:a",
            "aac",
            "-c:v",
            "libx264",
            "-preset",
            "fast",
            "-movflags",
            "+faststart",
            str(output_path.resolve()),
        ]

    elif crop_mode == "webcam_chat_stack":

        scale_crop = (
            f"scale="
            f"{width}:"
            f"{height}:"
            f"force_original_aspect_ratio=increase,"
            f"crop="
            f"{width}:"
            f"{height}"
        )

        vf_fallback_parts = [
            scale_crop,
        ]

        if color_filter:
            vf_fallback_parts.append(
                color_filter
            )

        vf_fallback = ",".join(
            vf_fallback_parts
        )

        cmd = [
            "ffmpeg",
            "-y",
            "-ss",
            str(start_sec),
            "-i",
            str(video_path.resolve()),
            "-t",
            str(duration),
            "-avoid_negative_ts",
            "make_zero",
            "-vf",
            vf_fallback,
            "-c:a",
            "aac",
            "-c:v",
            "libx264",
            "-preset",
            "fast",
            "-movflags",
            "+faststart",
            str(output_path.resolve()),
        ]

    elif crop_mode in (
        "bottom_split_stack",
        "bottom_split_stack_swapped",
    ):

        stack_order = (
            "[br][bl]"
            if crop_mode
            == "bottom_split_stack_swapped"
            else "[bl][br]"
        )

        if center_crop:

            fc = (
                "[0:v]"
                + center_crop
                + "[vc];"

                "[vc]"
                "split=2"
                "[blin][brin];"

                "[blin]"
                "crop="
                "in_w/2:"
                "in_h/2:"
                "0:"
                "in_h/2"
                "[bl];"

                "[brin]"
                "crop="
                "in_w/2:"
                "in_h/2:"
                "in_w/2:"
                "in_h/2"
                "[br];"

                f"{stack_order}"
                "vstack=inputs=2"
                "[stk];"

                "[stk]"
                "scale=1080:1920:"
                "force_original_aspect_ratio=increase,"
                "crop=1080:1920"
                "[out]"
            )

        else:

            fc = (
                "[0:v]"
                "split=2"
                "[blin][brin];"

                "[blin]"
                "crop="
                "in_w/2:"
                "in_h/2:"
                "0:"
                "in_h/2"
                "[bl];"

                "[brin]"
                "crop="
                "in_w/2:"
                "in_h/2:"
                "in_w/2:"
                "in_h/2"
                "[br];"

                f"{stack_order}"
                "vstack=inputs=2"
                "[stk];"

                "[stk]"
                "scale=1080:1920:"
                "force_original_aspect_ratio=increase,"
                "crop=1080:1920"
                "[out]"
            )

        fc, fc_output_label = _apply_color_to_filter_complex(
            fc,
            color_filter,
        )

        cmd = [
            "ffmpeg",
            "-y",
            "-ss",
            str(start_sec),
            "-i",
            str(video_path.resolve()),
            "-t",
            str(duration),
            "-avoid_negative_ts",
            "make_zero",
            "-filter_complex",
            fc,
            "-map",
            fc_output_label,
            "-map",
            "0:a?",
            "-c:a",
            "aac",
            "-c:v",
            "libx264",
            "-preset",
            "fast",
            "-movflags",
            "+faststart",
            str(output_path.resolve()),
        ]

    else:

        cmd = [
            "ffmpeg",
            "-y",
            "-ss",
            str(start_sec),
            "-i",
            str(video_path.resolve()),
            "-t",
            str(duration),
            "-avoid_negative_ts",
            "make_zero",
        ]

        if vf:
            cmd += [
                "-vf",
                vf,
            ]

        cmd += [
            "-c:a",
            "aac",
            "-c:v",
            "libx264",
            "-preset",
            "fast",
            "-movflags",
            "+faststart",
            str(output_path.resolve()),
        ]

    result = subprocess.run(
        cmd,
        cwd=str(out_dir),
        capture_output=True,
        text=True,
    )

    # FFmpeg built without libass has no subtitles filter.
    # Retry without captions if needed.
    if result.returncode != 0:

        err = (
            (result.stderr or "")
            + (result.stdout or "")
        )

        if (
            vf_parts is not None
            and (
                (
                    "No such filter" in err
                    and "subtitles" in err
                )
                or "Filter not found" in err
            )
        ):

            vf_no_subs = ",".join(
                vf_parts[:-1]
                if (
                    srt_path
                    and srt_path.exists()
                )
                else vf_parts
            )

            cmd = [
                "ffmpeg",
                "-y",
                "-ss",
                str(start_sec),
                "-i",
                str(video_path.resolve()),
                "-t",
                str(duration),
                "-avoid_negative_ts",
                "make_zero",
            ]

            if vf_no_subs:
                cmd += [
                    "-vf",
                    vf_no_subs,
                ]

            cmd += [
                "-c:a",
                "aac",
                "-c:v",
                "libx264",
                "-preset",
                "fast",
                "-movflags",
                "+faststart",
                str(output_path.resolve()),
            ]

            result = subprocess.run(
                cmd,
                cwd=str(out_dir),
                capture_output=True,
                text=True,
            )

    if result.returncode != 0:

        raise RuntimeError(
            "FFmpeg failed "
            f"(exit {result.returncode}): "
            f"{result.stderr or result.stdout}"
        )

    return output_path


def _probe_fps(
    video_path: Path,
) -> float | None:
    """
    Return source FPS via ffprobe.

    Returns None on failure.
    """
    try:
        out = subprocess.run(
            [
                "ffprobe",
                "-v",
                "error",
                "-select_streams",
                "v:0",
                "-show_entries",
                "stream=avg_frame_rate",
                "-of",
                "csv=p=0",
                str(video_path.resolve()),
            ],
            capture_output=True,
            text=True,
            timeout=10,
        )

        raw = (
            out.stdout
            or ""
        ).strip()

        if "/" in raw:
            num, den = raw.split(
                "/",
                1,
            )

            num_f = float(num)

            den_raw = float(den)

            den_f = (
                den_raw
                if den_raw != 0
                else 1.0
            )

            return (
                num_f / den_f
                if num_f > 0
                else None
            )

        if raw:
            return float(raw)

    except Exception:
        pass

    return None


def _focus_x_at_time(
    focus_track: list[
        tuple[
            float,
            float,
        ]
    ],
    time_sec: float,
) -> float:
    """
    Interpolate horizontal focus position at a specific clip time.

    focus_track contains:

        (
            seconds_from_clip_start,
            normalized_x,
        )

    Linear interpolation makes movement smooth between detector samples.
    """
    if not focus_track:
        return 0.5

    if len(focus_track) == 1:
        return max(
            0.0,
            min(
                1.0,
                float(
                    focus_track[0][1]
                ),
            ),
        )

    if time_sec <= focus_track[0][0]:
        return max(
            0.0,
            min(
                1.0,
                float(
                    focus_track[0][1]
                ),
            ),
        )

    if time_sec >= focus_track[-1][0]:
        return max(
            0.0,
            min(
                1.0,
                float(
                    focus_track[-1][1]
                ),
            ),
        )

    for i in range(
        len(focus_track) - 1
    ):
        t0, x0 = focus_track[i]
        t1, x1 = focus_track[i + 1]

        if t0 <= time_sec <= t1:

            span = t1 - t0

            if span <= 0:
                return max(
                    0.0,
                    min(
                        1.0,
                        float(x1),
                    ),
                )

            progress = (
                time_sec - t0
            ) / span

            x = (
                x0
                + (x1 - x0)
                * progress
            )

            return max(
                0.0,
                min(
                    1.0,
                    float(x),
                ),
            )

    return 0.5


def make_short_focus_track(
    video_path: Path,
    start_sec: float,
    end_sec: float,
    output_path: Path,
    focus_track: list[
        tuple[
            float,
            float,
        ]
    ],
    srt_path: Path | None = None,
    width: int = 1080,
    height: int = 1920,
    fps: float | None = None,
    color_preset: str = "none",
) -> Path:
    """
    Render a dynamic 9:16 crop using the horizontal face track
    produced by estimate_focus_track().

    The detector does not need to run every frame.

    Example input:

        [
            (0.0, 0.25),
            (0.5, 0.27),
            (1.0, 0.72),
        ]

    We interpolate between these points for every source frame.

    This produces smooth camera movement rather than sudden jumps.
    """
    import cv2
    import numpy as np

    output_path = Path(
        output_path
    )

    output_path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    duration = max(
        0.01,
        end_sec - start_sec,
    )

    src_fps = (
        fps
        if fps and fps > 0
        else (
            _probe_fps(video_path)
            or 30.0
        )
    )

    cap = cv2.VideoCapture(
        str(video_path)
    )

    if not cap.isOpened():
        raise RuntimeError(
            "OpenCV could not open "
            f"{video_path}"
        )

    src_w = int(
        cap.get(
            cv2.CAP_PROP_FRAME_WIDTH
        )
    )

    src_h = int(
        cap.get(
            cv2.CAP_PROP_FRAME_HEIGHT
        )
    )

    if src_w <= 0 or src_h <= 0:

        cap.release()

        raise RuntimeError(
            "Invalid source dimensions "
            f"{src_w}x{src_h}"
        )

    # Calculate the largest 9:16 crop that fits
    # inside the source video.
    target_aspect = (
        width / height
    )

    crop_h = src_h

    crop_w = int(
        round(
            crop_h
            * target_aspect
        )
    )

    if crop_w > src_w:

        crop_w = src_w

        crop_h = int(
            round(
                crop_w
                / target_aspect
            )
        )

    # H264 / yuv420p prefers even dimensions.
    crop_w = max(
        2,
        crop_w - (crop_w % 2),
    )

    crop_h = max(
        2,
        crop_h - (crop_h % 2),
    )

    max_x = max(
        0,
        src_w - crop_w,
    )

    max_y = max(
        0,
        src_h - crop_h,
    )

    total_frames = max(
        1,
        int(
            round(
                duration
                * src_fps
            )
        ),
    )

    vf_parts: list[str] = []

    color_filter = get_color_filter(
        color_preset
    )

    if color_filter:
        vf_parts.append(
            color_filter
        )

    if (
        srt_path
        and srt_path.exists()
    ):
        vf_parts.append(
            "subtitles="
            f"filename="
            f"{_escape_subtitles_path(srt_path.name)}"
        )

    vf = (
        ",".join(vf_parts)
        if vf_parts
        else None
    )

    cmd = [
        "ffmpeg",
        "-y",

        # Video comes from OpenCV.
        "-f",
        "rawvideo",
        "-pix_fmt",
        "bgr24",
        "-s",
        f"{width}x{height}",
        "-r",
        f"{src_fps:.6f}",
        "-i",
        "-",

        # Audio comes from the original source.
        "-ss",
        str(start_sec),
        "-t",
        str(duration),
        "-i",
        str(video_path.resolve()),
    ]

    if vf:
        cmd += [
            "-vf",
            vf,
        ]

    cmd += [
        "-map",
        "0:v",
        "-map",
        "1:a?",
        "-c:v",
        "libx264",
        "-preset",
        "fast",
        "-pix_fmt",
        "yuv420p",
        "-c:a",
        "aac",
        "-movflags",
        "+faststart",
        "-shortest",
        str(output_path.resolve()),
    ]

    # Seek OpenCV to clip start.
    cap.set(
        cv2.CAP_PROP_POS_MSEC,
        start_sec * 1000.0,
    )

    proc = subprocess.Popen(
        cmd,
        stdin=subprocess.PIPE,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.PIPE,
        cwd=str(
            output_path.parent
        ),
    )

    written = 0

    last_frame_bytes: bytes | None = None

    try:

        for i in range(
            total_frames
        ):

            ok, frame = cap.read()

            if (
                not ok
                or frame is None
            ):

                if last_frame_bytes is None:
                    break

                if proc.stdin:
                    proc.stdin.write(
                        last_frame_bytes
                    )

                written += 1

                continue

            # Current time relative to clip start.
            frame_time = (
                i / src_fps
            )

            # Interpolate detector positions.
            cx = _focus_x_at_time(
                focus_track,
                frame_time,
            )

            # For this version we track horizontally only.
            cy = 0.5

            # Convert normalized center to source pixels.
            px = int(
                round(
                    cx * src_w
                    - crop_w / 2.0
                )
            )

            py = int(
                round(
                    cy * src_h
                    - crop_h / 2.0
                )
            )

            # Prevent crop from leaving the frame.
            px = max(
                0,
                min(
                    max_x,
                    px,
                ),
            )

            py = max(
                0,
                min(
                    max_y,
                    py,
                ),
            )

            crop = frame[
                py:py + crop_h,
                px:px + crop_w,
            ]

            if (
                crop.shape[1] != width
                or crop.shape[0] != height
            ):
                crop = cv2.resize(
                    crop,
                    (
                        width,
                        height,
                    ),
                    interpolation=cv2.INTER_LANCZOS4,
                )

            if not crop.flags[
                "C_CONTIGUOUS"
            ]:
                crop = (
                    np.ascontiguousarray(
                        crop
                    )
                )

            last_frame_bytes = (
                crop.tobytes()
            )

            if proc.stdin:
                proc.stdin.write(
                    last_frame_bytes
                )

            written += 1

    finally:

        cap.release()

        try:
            if proc.stdin:
                proc.stdin.close()

        except Exception:
            pass

    stderr = (
        proc.stderr.read().decode(
            "utf-8",
            errors="replace",
        )
        if proc.stderr
        else ""
    )

    proc.wait()

    if proc.returncode != 0:

        # Retry without subtitles when FFmpeg
        # does not have the libass/subtitles filter.
        if (
            vf
            and (
                "No such filter" in stderr
                or "Filter not found" in stderr
                or "subtitles" in stderr.lower()
            )
        ):

            return make_short_focus_track(
                video_path=video_path,
                start_sec=start_sec,
                end_sec=end_sec,
                output_path=output_path,
                focus_track=focus_track,
                srt_path=None,
                width=width,
                height=height,
                fps=src_fps,
                color_preset=color_preset,
            )

        raise RuntimeError(
            "FFmpeg dynamic focus crop failed "
            f"(exit {proc.returncode}, "
            f"wrote {written}/{total_frames} frames):\n"
            f"{stderr}"
        )

    return output_path


def make_short_dynamic(
    video_path: Path,
    start_sec: float,
    end_sec: float,
    output_path: Path,
    per_frame_track: "list[TrackPoint]",
    srt_path: Path | None = None,
    width: int = 1080,
    height: int = 1920,
    fps: float | None = None,
    color_preset: str = "none",
) -> Path:
    """
    Render a 9:16 clip whose crop window follows
    an existing per-frame TrackPoint track.

    This original function is kept for compatibility
    with the rest of AutoShorts.
    """
    import cv2
    import numpy as np

    output_path = Path(
        output_path
    )

    output_path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    duration = max(
        0.01,
        end_sec - start_sec,
    )

    src_fps = (
        fps
        if fps and fps > 0
        else (
            _probe_fps(video_path)
            or 30.0
        )
    )

    cap = cv2.VideoCapture(
        str(video_path)
    )

    if not cap.isOpened():
        raise RuntimeError(
            f"OpenCV could not open {video_path}"
        )

    src_w = int(
        cap.get(
            cv2.CAP_PROP_FRAME_WIDTH
        )
    )

    src_h = int(
        cap.get(
            cv2.CAP_PROP_FRAME_HEIGHT
        )
    )

    if src_w <= 0 or src_h <= 0:

        cap.release()

        raise RuntimeError(
            f"Invalid source dimensions "
            f"{src_w}x{src_h}"
        )

    target_aspect = (
        width / height
    )

    crop_h = src_h

    crop_w = int(
        round(
            crop_h
            * target_aspect
        )
    )

    if crop_w > src_w:

        crop_w = src_w

        crop_h = int(
            round(
                crop_w
                / target_aspect
            )
        )

    crop_w = max(
        2,
        crop_w - (crop_w % 2),
    )

    crop_h = max(
        2,
        crop_h - (crop_h % 2),
    )

    max_x = max(
        0,
        src_w - crop_w,
    )

    max_y = max(
        0,
        src_h - crop_h,
    )

    total_frames = max(
        1,
        int(
            round(
                duration
                * src_fps
            )
        ),
    )

    vf_parts = []

    color_filter = get_color_filter(
        color_preset
    )

    if color_filter:
        vf_parts.append(
            color_filter
        )

    if (
        srt_path
        and srt_path.exists()
    ):
        vf_parts.append(
            "subtitles="
            f"filename="
            f"{_escape_subtitles_path(srt_path.name)}"
        )

    vf = (
        ",".join(vf_parts)
        if vf_parts
        else None
    )

    cmd = [
        "ffmpeg",
        "-y",
        "-f",
        "rawvideo",
        "-pix_fmt",
        "bgr24",
        "-s",
        f"{width}x{height}",
        "-r",
        f"{src_fps:.6f}",
        "-i",
        "-",
        "-ss",
        str(start_sec),
        "-t",
        str(duration),
        "-i",
        str(video_path.resolve()),
    ]

    if vf:
        cmd += [
            "-vf",
            vf,
        ]

    cmd += [
        "-map",
        "0:v",
        "-map",
        "1:a?",
        "-c:v",
        "libx264",
        "-preset",
        "fast",
        "-pix_fmt",
        "yuv420p",
        "-c:a",
        "aac",
        "-movflags",
        "+faststart",
        str(output_path.resolve()),
    ]

    cap.set(
        cv2.CAP_PROP_POS_MSEC,
        start_sec * 1000.0,
    )

    proc = subprocess.Popen(
        cmd,
        stdin=subprocess.PIPE,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.PIPE,
        cwd=str(
            output_path.parent
        ),
    )

    written = 0

    last_frame_bytes: bytes | None = None

    try:

        for i in range(
            total_frames
        ):

            ok, frame = cap.read()

            if (
                not ok
                or frame is None
            ):

                if last_frame_bytes is None:
                    break

                if proc.stdin:
                    proc.stdin.write(
                        last_frame_bytes
                    )

                written += 1
                continue

            if i < len(
                per_frame_track
            ):

                tp = per_frame_track[i]

                cx = tp.cx
                cy = tp.cy

            elif per_frame_track:

                tp = per_frame_track[-1]

                cx = tp.cx
                cy = tp.cy

            else:

                cx = 0.5
                cy = 0.5

            px = int(
                round(
                    cx * src_w
                    - crop_w / 2.0
                )
            )

            py = int(
                round(
                    cy * src_h
                    - crop_h / 2.0
                )
            )

            px = max(
                0,
                min(
                    max_x,
                    px,
                ),
            )

            py = max(
                0,
                min(
                    max_y,
                    py,
                ),
            )

            crop = frame[
                py:py + crop_h,
                px:px + crop_w,
            ]

            if (
                crop.shape[1] != width
                or crop.shape[0] != height
            ):

                crop = cv2.resize(
                    crop,
                    (
                        width,
                        height,
                    ),
                    interpolation=cv2.INTER_LANCZOS4,
                )

            if not crop.flags[
                "C_CONTIGUOUS"
            ]:

                crop = (
                    np.ascontiguousarray(
                        crop
                    )
                )

            last_frame_bytes = (
                crop.tobytes()
            )

            if proc.stdin:
                proc.stdin.write(
                    last_frame_bytes
                )

            written += 1

    finally:

        cap.release()

        try:
            if proc.stdin:
                proc.stdin.close()

        except Exception:
            pass

    stderr = (
        proc.stderr.read().decode(
            "utf-8",
            errors="replace",
        )
        if proc.stderr
        else ""
    )

    proc.wait()

    if proc.returncode != 0:

        if (
            vf
            and (
                "No such filter" in stderr
                or "Filter not found" in stderr
                or "subtitles" in stderr.lower()
            )
        ):

            return make_short_dynamic(
                video_path,
                start_sec,
                end_sec,
                output_path,
                per_frame_track,
                srt_path=None,
                width=width,
                height=height,
                fps=src_fps,
                color_preset=color_preset,
            )

        raise RuntimeError(
            "FFmpeg dynamic-crop failed "
            f"(exit {proc.returncode}, "
            f"wrote {written}/{total_frames} frames):\n"
            f"{stderr}"
        )

    return output_path


def _escape_subtitles_path(
    path: str,
) -> str:
    """
    Escape path for use inside
    FFmpeg subtitles filter.
    """
    safe = (
        path
        .replace(
            "\\",
            "\\\\",
        )
        .replace(
            ":",
            "\\:",
        )
        .replace(
            "'",
            "\\'",
        )
    )

    if not any(
        c in safe
        for c in " ,;[]"
    ):
        return safe

    return f"'{safe}'"


def write_srt(
    segments: list[dict],
    path: Path,
    start_offset: float = 0.0,
) -> None:
    """
    Write SRT from segments.

    Segment times are absolute.
    start_offset shifts display.
    """
    path = Path(path)

    path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    lines = []

    for i, s in enumerate(
        segments,
        1,
    ):

        t0 = (
            s["start"]
            - start_offset
        )

        t1 = (
            s["end"]
            - start_offset
        )

        if t0 < 0:
            t0 = 0.0

        lines.append(
            f"{i}"
        )

        lines.append(
            f"{_ts(t0)} --> "
            f"{_ts(t1)}"
        )

        lines.append(
            s.get(
                "text",
                "",
            ).replace(
                "\n",
                " ",
            )
        )

        lines.append("")

    path.write_text(
        "\n".join(lines),
        encoding="utf-8",
    )


def _ts(
    sec: float,
) -> str:

    h = int(
        sec // 3600
    )

    m = int(
        (sec % 3600)
        // 60
    )

    s = (
        sec % 60
    )

    return (
        f"{h:02d}:"
        f"{m:02d}:"
        f"{int(s):02d},"
        f"{int(s % 1 * 1000):03d}"
    )
